#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# brew packages Mac
# amethyst fzf nvim exa hugo bash-completion@2 newsboat kubectl

# ubuntu packages apt
# ripgrep gh

# ubuntu apt neovim setup
# gcc g++ unzip

# ubuntu brew
# fd fzf kubectl kubectx derailed/k9s/k9s

# ubuntu brew for neovim setup
# neovim go lazygit

# ubuntu specific notes
# create symbolic link to neovim from vim. when not using neovim on
# Ubuntu systems, because I use the v alias everywhere.
# sudo ln -sf /usr/bin/vim /usr/bin/nvim

# ubuntu neovim setup
# there is an issue with npm on wsl ubuntu 22. Use this to install npm: https://stackoverflow.com/questions/73673804/npm-show-npm-elf-not-found-error-in-wsl

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash

# set up git prompt
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >"$XDG_CONFIG_HOME"/bash/git-prompt.sh

# Symbolic links

# ln -s ./.amethyst.yml "$HOME"/.amethyst.yml
# toto: config for iterm
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

# Second Brain
# This one's a little tricky because the path contains a space. It needs to be stored as an array,
# and when called it needs to be quoted.
export SECOND_BRAIN=("/Users/jamestench//Library/Mobile Documents/iCloud~md~obsidian/Documents/MyBrain")
ln -sf "$SECOND_BRAIN" ~/brain
#
# iCloud
# export ICLOUD=("/Users/jamestench/Library/Mobile Documents/com~apple~CloudDocs")
# ln -sf "$ICLOUD" ~/icloud
